AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: backend – /suggest-literature y /booking

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 6

Parameters:
  OpenAIKey:
    Type: String
    Description: OpenAI API key (sk-…)
    Default: dummy

Resources:
  ##########################
  # HTTP API con CORS
  ##########################
  AppHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - http://localhost:5174
          - https://storage-sizer-demo.vercel.app
        AllowMethods: ["POST", "OPTIONS"]
        AllowHeaders: ["Content-Type"]

  #######################################
  # DynamoDB tabla bookings
  #######################################
  BookingsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: bookings
      PrimaryKey:
        Name: bookingId
        Type: String

  ############################################
  # Lambda GenAI  –  POST /suggest-literature
  ############################################
  SuggestLiteratureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: suggest-literature/
      Handler: suggestLiterature.handler
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppHttpApi
            Path: /suggest-literature
            Method: post

  ###########################################
  # Lambda booking  –  POST /booking
  ###########################################
  BookUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: book-unit.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref BookingsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookingsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppHttpApi
            Path: /booking
            Method: post

Outputs:
  SuggestLiteratureApi:
    Description: URL /suggest-literature
    Value: !Sub "https://${AppHttpApi}.execute-api.${AWS::Region}.amazonaws.com/suggest-literature"

  BookUnitApi:
    Description: URL /booking
    Value: !Sub "https://${AppHttpApi}.execute-api.${AWS::Region}.amazonaws.com/booking"
